
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 12.0.0.0/24

services:
  database-postgresql:
    build:
      dockerfile: ./docker/database-postgresql/Dockerfile
      args:
        ENVIRONMENT: ${ENV_DEV}
    ports:
      - '${POSTGRES_PUBLIC_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      network:
        ipv4_address: ${POSTGRES_PUBLIC_HOST}

  api-fastify:
    build:
      dockerfile: ./docker/api-fastify/Dockerfile
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_PUBLIC_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - '${API_PUBLIC_PORT}:${API_PORT}'
    networks:
      network:
        ipv4_address: ${API_PUBLIC_HOST}

  web-vite:
    build:
      dockerfile: ./docker/web-vite/Dockerfile
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - '${WEB_PUBLIC_PORT}:${WEB_PORT}'
    networks:
      network:
        ipv4_address: ${WEB_PUBLIC_HOST}
