name: Github Actions
run-name: ${{ github.actor }} is running Github Actions 🚀
on:
  push:
    branches:
      - '*'

jobs:
  build-dev:
    name: Build docker dev
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1

  test-api-chi-service-moviecategory-dev:
    name: Build and test docker api-chi service moviecategory dev
    runs-on: ubuntu-24.04
    needs: [ build-dev ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi service
      run: sh scripts/test.bash api-service-moviecategory

  test-api-chi-service-movie-dev:
    name: Build and test docker api-chi service movie dev
    runs-on: ubuntu-24.04
    needs: [ build-dev ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi service
      run: sh scripts/test.bash api-service-movie

  test-api-chi-service-moviedependmoviecategory-dev:
    name: Build and test docker api-chi service moviedependmoviecategory dev
    runs-on: ubuntu-24.04
    needs: [ build-dev ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi service
      run: sh scripts/test.bash api-service-moviedependmoviecategory

  test-api-chi-service-moviedirecator-dev:
    name: Build and test docker api-chi service moviedirecator dev
    runs-on: ubuntu-24.04
    needs: [ build-dev ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi service
      run: sh scripts/test.bash api-service-moviedirecator

  test-api-chi-route-moviecategory-dev:
    name: Build and test docker api-chi route moviecategory dev
    runs-on: ubuntu-24.04
    needs: [ build-dev ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services: |
          database-postgresql
          api-chi

    - name: Test api-chi service
      run: sh scripts/test.bash api-route-moviecategory

  lint-api-chi:
    name: Lint api-chi
    runs-on: ubuntu-24.04
    needs: [ build-dev ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.7
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        working-directory: ./api-chi

  build-nix:
    name: Build on nix
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup nix
      uses: cachix/install-nix-action@v27

    - name: Enter nix flake devshell
      run: nix develop .
      if: always()